#!/usr/bin/env python2.7

import sys
import subprocess
import argparse

import ytad.config.authorization

def _get_args():
    p = argparse.ArgumentParser()

    p.add_argument(
        'token',
        help='Authorization token')

    args = p.parse_args()
    return args

def _main():
    args = _get_args()

    cmd = [
        'gaa_authorize',
        ytad.config.authorization.SERVICE_NAME,
        ytad.config.authorization.SERVICE_VERSION,
        ytad.config.authorization.GOOGLE_API_CLIENT_ID,
        ytad.config.authorization.GOOGLE_API_CLIENT_SECRET,
        '-t', args.token,
    ]

    for scope in ytad.config.authorization.API_SCOPES:
        cmd += [
            '--scope', scope,
        ]

    p = subprocess.Popen(cmd)
    r = p.wait()

    if r != 0:
        print("Could not write authorization.")
        sys.exit(1)

if __name__ == '__main__':
    _main()
