#!/usr/bin/env python2.7

from __future__ import unicode_literals

import os
import sys
_APP_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, _APP_PATH)

import logging
import argparse

import youtube_dl

import ytad.config.log
import ytad.client_manager
import ytad.helper.playlists

_LOGGER = logging.getLogger(__name__)

_DESCRIPTION = "YouTube video autodownloader."

def _get_args():
    parser = \
        argparse.ArgumentParser(
            description=_DESCRIPTION)

    parser.add_argument(
        'title',
        help="Playlist title")

    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help="Increase verbosity")

    args = parser.parse_args()
    return args

def _main():
    args = _get_args()
    ytad.config.log.configure(args.verbose)

    cm = ytad.client_manager.get_client_manager()
    p = ytad.helper.playlists.Playlists(cm)
    playlists = p.find_all_in_mine(args.title)
    playlists = list(playlists)

    if not playlists:
        print("Playlist(s) not found.")
        sys.exit(2)
    else:
        for playlist in playlists:
            print(playlist.id)

if __name__ == '__main__':
    _main()
