#!/usr/bin/env python2.7

import os
import sys
_APP_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, _APP_PATH)

import logging
import argparse

import ytad.config.log
import ytad.download
import ytad.client_manager

_LOGGER = logging.getLogger(__name__)

_DESCRIPTION = "YouTube video autodownloader."

def _get_args():
    parser = \
        argparse.ArgumentParser(
            description=_DESCRIPTION)

    parser.add_argument(
        'playlist_id',
        help="Playlist ID")

    parser.add_argument(
        '-dp', '--download-path',
        help="Local download path. Omit to update but not download.")

    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help="Increase verbosity")

    args = parser.parse_args()
    return args

def _main():
    args = _get_args()
    ytad.config.log.configure(args.verbose)

    cm = ytad.client_manager.get_client_manager()
    d = ytad.download.Download(cm)
    d.check_and_download(args.playlist_id, download_path=args.download_path)

if __name__ == '__main__':
    _main()
